class Callback:
    """
    Base class for callbacks. Users can subclass and override any of:
      - on_train_begin(logs)
      - on_train_end(logs)
      - on_epoch_begin(epoch, logs)
      - on_epoch_end(epoch, logs)
      - on_train_batch_end(batch, logs)
    """

    def on_train_begin(self, logs: dict[str, float] | None = None): ...
    def on_train_end(self, logs: dict[str, float] | None = None): ...
    def on_epoch_begin(self, epoch: int, logs: dict[str, float] | None = None): ...
    def on_epoch_end(self, epoch: int, logs: dict[str, float] | None = None): ...
    def on_train_batch_end(self, batch: int, logs: dict[str, float] | None = None): ...
